import Link from "next/link";
import "./globals.css";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import LogoutButton from "@/components/LogoutButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get supabase
  const supabase = createServerComponentClient({ cookies });

  // get user
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className="min-h-screen text-white bg-background">
        <nav className="flex justify-between px-10 py-4 text-white border-b w-fullgap-5 border-b-foreground/10">
          <div className="flex gap-6 my-auto">
            <Link href="/">Home</Link>
            <Link href="/community/all">Communities</Link>
            <Link href={`/user/${user?.id}`}>Profile</Link>
          </div>
          <div>
            {user ? (
              <div className="flex items-center gap-4">
                <LogoutButton />
              </div>
            ) : (
              <Link
                href="/login"
                className="px-4 py-2 no-underline rounded-md bg-btn-background hover:bg-btn-background-hover"
              >
                Login
              </Link>
            )}
          </div>
        </nav>

        <main className="flex flex-col items-center pt-5 bg-background">
          {children}
        </main>
      </body>
    </html>
  );
}
